controller: {}
workers:
- realms:
  - name: kotori-realm
    roles:
    - name: anonymous
      permissions:
      - {call: true, publish: true, register: true, subscribe: true, uri: '*'}
  transports:
  - endpoint: {port: 9000, type: tcp}
    paths:
      /: {directory: .., type: static}
      #/: {url: "http://localhost:35000", type: redirect}
      ws: {type: websocket}
    type: web
  type: router
